### ISSUE TITLE
(ansible-handler) state=absent is not always the expected undo state

### ISSUE THREAD

**Issue by mieel** [stacklio/stackl#233] opened 2021-04-20 16:30 UTC
# Expected Result
running stackl `delete` should undo the `apply` of a role

# Actual Result
when a role specifies something as `absent` as a feature, this state won't be undone because the delete command sets state=absent in all case.

**Comment by stgrace** [comment] 2021-04-28 12:46
Duplicate of https://github.com/stacklio/stackl/issues/240

**Closed by stgrace** 2021-04-28 12:46 UTC
